### ISSUE TITLE
[ Tenant Infra Controller ] Ability to Support Low Priority Nodes ( Spot, Virutal Machines and Preemptible )

### ISSUE THREAD

**Issue by AdheipSingh** [baazhq/baaz#77]
1. Tenant Infra Controller to be able to create spot nodes. 
2. For every spot nodegroup create dedicated nodegroup.
3. Research on label consistency ie if a pod is having labels for both spot as well as dedicated. How does the scheduler behave ?
4. Sub task for this is too make sure dataplane is bootstrapped with Cluster Autoscaler for EKS. For GKE autoscaler is already available. 

```
tenantsInfra:
  druid-small:
    machinePool:
    - name: druid-dataservers
      size: t2.small
      min: 1
      max: 3
      strictScheduling: enable
      type: low-priority
      labels:
        app: druid
        size: small
 ```
